version: '3.3'
services:
  netdata:
    restart: unless-stopped
    container_name: netdata
    hostname: netdata.${DOMAINNAME}
    image: netdata/netdata
    networks:
      - traefik
      - socketproxy
      - influxdb
    environment:
      - VIRTUALIZATION=kvm
      - DOCKER_HOST=socketproxy:2375
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - ${CONFIG_FOLDER}/netdata/netdata.conf:/etc/netdata/netdata.conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.netdata.tls.certresolver=letsencrypt"
      - "traefik.http.routers.netdata.rule=Host(`docker.netdata.${DOMAINNAME}`)"
      - "traefik.http.routers.netdata.entrypoints=https"
      - "traefik.http.routers.netdata.middlewares=secureheaders, ipwhitelist"
      - "traefik.http.services.netdata.loadbalancer.server.port=19999"

  influxdb:
    restart: unless-stopped
    image: influxdb
    container_name: influxdb
    networks:
      - traefik
      - influxdb
    volumes:
      - ${CONFIG_FOLDER}/influxdb/data:/var/lib/influxdb
      - ${CONFIG_FOLDER}/influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    command:
      - '-config'
      - '/etc/influxdb/influxdb.conf'
  
  chronograf:
    image: chronograf
    container_name: chronograf
    networks:
      - traefik
      - influxdb
    restart: unless-stopped
    volumes:
      - ${CONFIG_FOLDER}/chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.chronograf.rule=Host(`chronograf.${DOMAINNAME}`)"
      - "traefik.http.routers.chronograf.entrypoints=https"
      - "traefik.http.routers.chronograf.tls=true"
      - "traefik.http.routers.chronograf.middlewares=secureheaders, ipwhitelist"
      - "traefik.http.services.chronograf.loadbalancer.server.port=8888"    

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    container_name: grafana
    networks:
      - traefik
      - influxdb
    volumes:
      - ${CONFIG_FOLDER}/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAINNAME}`)"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.middlewares=secureheaders, ipwhitelist"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  unifi-poller:
    restart: unless-stopped
    image: golift/unifi-poller
    container_name: unifi-poller
    networks:
      - traefik
    environment:
      - UP_INFLUXDB_DB=unifi
      - UP_INFLUXDB_USER=${INFLUXDB_ADMIN_USER}
      - UP_INFLUXDB_PASS=${INFLUXDB_ADMIN_PASSWORD}
      - UP_INFLUXDB_URL=http://influxdb:8086
      - UP_UNIFI_DEFAULT_USER=${UNIFI_USER}
      - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASS}
      - UP_UNIFI_DEFAULT_URL=${UNIFI_URL}
      - UP_POLLER_DEBUG=false

networks:
  traefik:
    external:
      name: traefik
  influxdb:
    external:
      name: influxdb
  socketproxy:
    external:
      name: socketproxy
